# Generated by Django 4.1.1 on 2022-09-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0007_medicamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
