# Generated by Django 4.1.1 on 2022-09-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0008_remove_person_doc_remove_venda_pessoa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='mg',
            field=models.IntegerField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
